Add the ability to identifiers from a configurable interpolated string with variables
ibissource/zaakbrug pull request #43
Opened 2023-02-10 17:05 UTC by RayetSena

2023-02-13 09:10 UTC, MLenterman requested changes

2023-02-13 09:10 UTC, MLenterman commented on src/main/configurations/Translate/DeploymentSpecifics.properties
> +NewIdDigit=00000
These variables are supposed to be calculated runtime. Prefixparam is no longer needed as it is part of the template string. The date should be gotten at runtime and should be current date/time the moment the new identifier is created.
NewIdDigit should simply be the new identifier with the formatting applied to it. So the {NewIdentificatie} variable used to update the database, can be used as input for the formatting xslt.

In the properties there should only be a template string like:
zaak-identificatie-template="ZK{datetime:yyyy}-{id:D5}"

2023-02-23 09:24 UTC, MLenterman requested changes

2023-02-23 09:24 UTC, MLenterman commented on src/main/configurations/Translate/Common/xsl/CreateIdentication.xslt
> +                        select="concat(format-dateTime(current-dateTime(), $date),'-')" />
Is missing a check for the optional ':', indicating that a format string follow. Without ':' it should just return current-dateTime without any formatting.

2023-02-23 09:24 UTC, MLenterman commented on src/main/configurations/Translate/DeploymentSpecifics.properties
> +zaak-identificatie-template=ZK{datetime:[Y0001]}-{id:D5}
The same mechanism should also be implemented for document identificatie with its own template in the DeploymentSpecifics.

2023-02-23 09:24 UTC, MLenterman commented on src/main/configurations/Translate/Configuration_GenereerIdentificatieEmulator.xml
> +                <Param name="zaak-identificatie-template" value="${zaak-identificatie-template}"/>
Zaak en document both have their own template string in the DeploymentSpecifics. Probably pass the template as session key to the adapter. While calling it from the genereerZaakIdentificatie and genereerDocumentIdentificatie adapters you can pass the correct one.

2023-03-14 10:45 UTC, philipsens approved these changes

2023-03-14 12:08 UTC, MLenterman approved these changes

2023-03-14 12:11 UTC, merged

2023-03-14 12:16 UTC, MLenterman commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on [GitHub release](https://github.com/ibissource/zaakbrug/releases/tag/v1.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: